name: print-a-word

on: push

jobs:
  print-a-word-job

    runs-on: ubuntu-latest

    steps:
      -name: Checkout repository
       uses: actions/checkout@v4
      -run: echo "$(cat hello_world.txt)" 
